### ISSUE TITLE
How to public to AWS Lambda with node_modules directory

### ISSUE THREAD

**Issue by Tan-nn** [vanister/contacts_api#1]
Dear @vanister 

Thank for your helpful demo, I try to deploy to AWS Lambda, and it successfully but without node_modules directory, then I google and add config below to `serverless.yml`
```
 package:
   excludeDevDependencies: false
```
`serverless framework` uploaded .zip file to Lambda `(is too large to enable inline code editing)` and try testing with endpoint it response error:
`{"message": "Internal server error"}`
- Can you teach me how can seed dynamodb on AWS (not localhost) ?!

p/s: localhost work fine

**Comment by vanister** [comment]
You can use the Resources section in the `serverless.yml` file to list the dynamo table for the Serverless cli to create. 

https://serverless.com/framework/docs/providers/aws/guide/resources/

To seed the table, I would just go to the AWS console online and manually add in an entry into the DynamoDB table once it's created.

You can use the exclude/include combination in the `serverless.yml` file to reduce your dependencies for deployment.  You can actually test the packaging locally before deploying to AWS through the Serverless cli.  The command is `serverless package`.

https://serverless.com/framework/docs/providers/aws/guide/packaging/

Hope this helps!
