### ISSUE TITLE
How to manage two yml files

### ISSUE THREAD

**Issue by nive745** [vanister/contacts_api#7]
Hello vanister,
Thank you so much for sharing this code. I got stuck in one minor issue. I am new to aws functions. Can you please help me to get rid of this problem ?
When i import two functions yml files i got only one url
`service: contacts-api

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

functions:
  - '${file(src/handlers/contacts/contacts.serverless.yml)}'
  - '${file(src/handlers/users/users.serverless.yml)}'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0 # for docker container hosting
`
I got url's 
`Serverless: Starting Offline: dev/us-west-2.

Serverless: Routes for list:
Serverless: GET /user/getall
Serverless: POST /{apiVersion}/functions/contacts-api-dev-list/invocations

Serverless: Routes for get:
Serverless: GET /user/{id}
Serverless: POST /{apiVersion}/functions/contacts-api-dev-get/invocations

Serverless: Routes for add:
Serverless: POST /user
Serverless: POST /{apiVersion}/functions/contacts-api-dev-add/invocations

Serverless: Routes for update:
Serverless: PUT /user/{id}
Serverless: POST /{apiVersion}/functions/contacts-api-dev-update/invocations

Serverless: Routes for delete:
Serverless: DELETE /user/{id}
Serverless: POST /{apiVersion}/functions/contacts-api-dev-delete/invocations

Serverless: Offline [HTTP] listening on http://0.0.0.0:3000
Serverless: Enter "rp" to replay the last request
`

Thanks in advance

**Comment by vanister** [comment]
I think what is happening is that you are overriding the `contacts.serverless.yml` file's entries.  Your `users.serverless.yml` file likely contain the same function names.

Try prefixing the names with `list-users`, `get-user`, etc. for `users.serverless.yml`.  Likewise, prefix the `contacts.serverless.yml` file with something similar to user, `list-contacts`, `get-contact`, etc.
